{
 "title": "Pipelines",
 "panels": [
  {
   "title": "Last Run Timestamp",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 6 },
   "targets": [
    { "expr": "ml_job_last_run_timestamp" }
   ]
  },
  {
   "title": "Pipeline Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "ml_job_success" }
   ]
  },
  {
   "title": "Pipeline Duration (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "ml_job_duration_seconds" }
   ]
  },
  {
   "title": "Drift Detected",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 4 },
   "targets": [
    {
     "expr": "ml_job_drift_detected{job=\"drift_check\"}"
    }
   ]
  }
 ]
}